### ISSUE TITLE
fails with Rails 5.0.0.beta2

### ISSUE THREAD

**Issue by DanielKehoe** [thoughtbot/high_voltage#220]
Using Rails 5.0.0.beta1, a request for a page fails with:
```
Routing Error
undefined method `hide_action' for HighVoltage::PagesController:Class

Rails.root: /Users/danielkehoe/workspace/wip/myapp

Application Trace | Framework Trace | Full Trace
high_voltage (2.4.0) app/controllers/concerns/high_voltage/static_page.rb:26:in `block in <module:StaticPage>'
activesupport (5.0.0.beta1) lib/active_support/concern.rb:120:in `class_eval'
activesupport (5.0.0.beta1) lib/active_support/concern.rb:120:in `append_features'
high_voltage (2.4.0) app/controllers/high_voltage/pages_controller.rb:2:in `include'
high_voltage (2.4.0) app/controllers/high_voltage/pages_controller.rb:2:in `<class:PagesController>'
high_voltage (2.4.0) app/controllers/high_voltage/pages_controller.rb:1:in `<top (required)>'
activesupport (5.0.0.beta1) lib/active_support/dependencies.rb:492:in `load'
activesupport (5.0.0.beta1) lib/active_support/dependencies.rb:492:in `block in load_file'
activesupport (5.0.0.beta1) lib/active_support/dependencies.rb:682:in `new_constants_in'
activesupport (5.0.0.beta1) lib/active_support/dependencies.rb:491:in `load_file'
activesupport (5.0.0.beta1) lib/active_support/dependencies.rb:388:in `block in require_or_load'
activesupport (5.0.0.beta1) lib/active_support/dependencies.rb:37:in `block in load_interlock'
activesupport (5.0.0.beta1) lib/active_support/dependencies/interlock.rb:12:in `block in loading'
activesupport (5.0.0.beta1) lib/active_support/concurrency/share_lock.rb:115:in `exclusive'
activesupport (5.0.0.beta1) lib/active_support/dependencies/interlock.rb:11:in `loading'
activesupport (5.0.0.beta1) lib/active_support/dependencies.rb:37:in `load_interlock'
activesupport (5.0.0.beta1) lib/active_support/dependencies.rb:369:in `require_or_load'
activesupport (5.0.0.beta1) lib/active_support/dependencies.rb:529:in `load_missing_constant'
activesupport (5.0.0.beta1) lib/active_support/dependencies.rb:212:in `const_missing'
activesupport (5.0.0.beta1) lib/active_support/inflector/methods.rb:261:in `const_get'
activesupport (5.0.0.beta1) lib/active_support/inflector/methods.rb:261:in `block in constantize'
activesupport (5.0.0.beta1) lib/active_support/inflector/methods.rb:257:in `each'
activesupport (5.0.0.beta1) lib/active_support/inflector/methods.rb:257:in `inject'
activesupport (5.0.0.beta1) lib/active_support/inflector/methods.rb:257:in `constantize'
activesupport (5.0.0.beta1) lib/active_support/dependencies.rb:601:in `get'
activesupport (5.0.0.beta1) lib/active_support/dependencies.rb:632:in `constantize'
actionpack (5.0.0.beta1) lib/action_dispatch/http/request.rb:93:in `controller_class'
actionpack (5.0.0.beta1) lib/action_dispatch/routing/route_set.rb:44:in `controller'
actionpack (5.0.0.beta1) lib/action_dispatch/routing/route_set.rb:30:in `serve'
actionpack (5.0.0.beta1) lib/action_dispatch/journey/router.rb:42:in `block in serve'
actionpack (5.0.0.beta1) lib/action_dispatch/journey/router.rb:29:in `each'
actionpack (5.0.0.beta1) lib/action_dispatch/journey/router.rb:29:in `serve'
actionpack (5.0.0.beta1) lib/action_dispatch/routing/route_set.rb:715:in `call'
actionview (5.0.0.beta1) lib/action_view/digestor.rb:14:in `call'
rack (2.0.0.alpha) lib/rack/etag.rb:25:in `call'
rack (2.0.0.alpha) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.0.alpha) lib/rack/head.rb:12:in `call'
rack (2.0.0.alpha) lib/rack/session/abstract/id.rb:220:in `context'
rack (2.0.0.alpha) lib/rack/session/abstract/id.rb:214:in `call'
actionpack (5.0.0.beta1) lib/action_dispatch/middleware/cookies.rb:608:in `call'
activerecord (5.0.0.beta1) lib/active_record/query_cache.rb:36:in `call'
activerecord (5.0.0.beta1) lib/active_record/connection_adapters/abstract/connection_pool.rb:963:in `call'
activerecord (5.0.0.beta1) lib/active_record/migration.rb:524:in `call'
actionpack (5.0.0.beta1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (5.0.0.beta1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.0.beta1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.0.beta1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0.beta1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (5.0.0.beta1) lib/action_dispatch/middleware/reloader.rb:71:in `call'
actionpack (5.0.0.beta1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.0.beta1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (3.0.0) lib/web_console/middleware.rb:27:in `call'
actionpack (5.0.0.beta1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.0.beta1) lib/rails/rack/logger.rb:42:in `call_app'
railties (5.0.0.beta1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.0.beta1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
activesupport (5.0.0.beta1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.0.beta1) lib/active_support/tagged_logging.rb:70:in `tagged'
railties (5.0.0.beta1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.0.beta1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.0.alpha) lib/rack/method_override.rb:22:in `call'
rack (2.0.0.alpha) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.0.beta1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.0.beta1) lib/action_dispatch/middleware/load_interlock.rb:13:in `call'
actionpack (5.0.0.beta1) lib/action_dispatch/middleware/static.rb:132:in `call'
rack (2.0.0.alpha) lib/rack/sendfile.rb:111:in `call'
railties (5.0.0.beta1) lib/rails/engine.rb:522:in `call'
puma (2.15.3) lib/puma/server.rb:541:in `handle_request'
puma (2.15.3) lib/puma/server.rb:388:in `process_client'
puma (2.15.3) lib/puma/server.rb:270:in `block in run'
puma (2.15.3) lib/puma/thread_pool.rb:106:in `call'
puma (2.15.3) lib/puma/thread_pool.rb:106:in `block in spawn_thread'

```

To duplicate the issue, install Rails 5.0.0.beta1. Then:
```
$ rails new myapp
```
Add to the Gemfile:
```
gem 'high_voltage', '~> 2.4.0'
```
Then:
```
$ mkdir app/views/pages
$ touch app/views/pages/about.html.erb
```
Then try the URL:
http://localhost:3000/pages/about

**Comment by jasnow** [comment]
Related ticket: https://github.com/thoughtbot/high_voltage/pull/214

**Comment by DanielKehoe** [comment]
Issue resolved in high_voltage 'master'.
